# =============================================================
# SmashEgg — Настройка шансов, звуков и сообщений
# Поддерживает MiniMessage (градиенты, HEX, клики)
# =============================================================

settings:
  # Нужно ли ломать яйцо при клике на спавнер?
  egg-break-on-spawner: true

  # Шанс (в %), что яйцо разобьется при попытке сменить моба в спавнере
  egg-break-chance: 30

  # Шанс (в %), что моб успешно заспавнится при клике на землю/стену
  # Если не везет — яйцо исчезает, а моб не появляется.
  ground-spawn-chance: 70

  # Список мобов, которых нельзя ставить в спавнер (вводить капсом)
  black-entities:
    - "ENDER_DRAGON"
    - "WITHER"
    - "WARDEN"

# Названия звуков (должны быть капсом)
sounds:
  success: "ENTITY_PLAYER_LEVELUP" # Успешная установка
  failure: "ENTITY_VILLAGER_NO"    # Неудача на земле
  denied: "BLOCK_ANVIL_LAND"       # Запрещенный моб
  egg-break: "BLOCK_GLASS_BREAK"   # Яйцо разбилось об спавнер

# Игровые сообщения (поддержка HEX цветов через <#RRGGBB>)
messages:
  usage: "<#E43A96>▶ <white>Использование: <#E43A96>/smashegg reload" # Если игрок ввел команду неправильно
  reload-success: "<#E43A96>▶ <white>Конфигурация <#E43A96>успешно <white>перезагружена!" # Сообщение при успешной перезагрузке плагина
  no-permission: "<#E43A96>▶ <#E43A96>У вас <#E43A96>нет <white>прав для этого." # Если у игрока нет прав (permission)
  egg-break: "<#E43A96>▶ <white>Яйцо <#E43A96>разбилось <white>при установке в спавнер!" # Когда яйцо ломается именно об спавнер
  ground-failure: "<#E43A96>▶ <white>Яйцо <#E43A96>разбилось в руках<white>, моб не появился!" # Когда яйцо ломается при клике на пол/землю
  denied: "<#E43A96>▶ <white>Этот тип моба <#E43A96>запрещен<white>!" # Если игрок пытается поставить моба из черного списка